[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, Position = 0, ValueFromRemainingArguments = $true)]
    [ValidateNotNullOrEmpty()]
    [string[]] $Name,
    [string] $OutputDirectory = (Get-Location).Path,
    [string[]] $SourcePath = @(),
    [switch] $Force
)

<#
.SYNOPSIS
Exports one or more real PowerShell functions as executable scripts.

.DESCRIPTION
22sc is the batch form of 2sc. It captures each requested function from the
current session, or from -SourcePath, and writes one <name>.ps1 file per
function. Lazy dispatcher wrappers are rejected so they cannot become
recursive, non-working scripts.
#>

function Get-22scSourceDefinition {
    param([string] $FunctionName, [string[]] $Paths)

    foreach ($path in $Paths) {
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { continue }
        $tokens = $null
        $errors = $null
        $ast = [System.Management.Automation.Language.Parser]::ParseFile($path, [ref] $tokens, [ref] $errors)
        if ($errors -and $errors.Count -gt 0) {
            throw "22sc: cannot parse '$path': $($errors[0].Message)"
        }
        $match = @($ast.FindAll({
            param($node)
            $node -is [System.Management.Automation.Language.FunctionDefinitionAst] -and
            (($node.Name -replace '^(?i:(global|script|local):)+', '') -ieq $FunctionName)
        }, $true) | Select-Object -First 1)
        if ($match.Count -gt 0) {
            return [pscustomobject]@{ Definition = $match[0].Extent.Text; Source = $path }
        }
    }
    return $null
}

$destination = [System.IO.Path]::GetFullPath($OutputDirectory)
if (-not (Test-Path -LiteralPath $destination -PathType Container)) {
    throw "22sc: output directory does not exist: $destination"
}

$plans = New-Object 'System.Collections.Generic.List[object]'
$seen = New-Object 'System.Collections.Generic.HashSet[string]' ([System.StringComparer]::OrdinalIgnoreCase)
foreach ($inputName in $Name) {
    $functionName = $inputName -replace '^(?i:(global|script|local):)+', ''
    if (-not $seen.Add($functionName)) { continue }

    $definition = $null
    $source = 'session'
    $command = Get-Command -Name $functionName -CommandType Function -ErrorAction SilentlyContinue
    if ($command) {
        $definition = "function $functionName {" + $command.Definition.Trim() + '}'
        if ($definition -match '(?i)\bInvoke-ProfileLazyFunction\b') {
            $profileModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
            if ($profileModule) {
                $savedText = & $profileModule {
                    param($requestedName)
                    Get-ProfileSavedFunctionText -Name $requestedName
                } $functionName
                if (-not [string]::IsNullOrWhiteSpace([string]$savedText)) {
                    $definition = [string]$savedText
                    $source = 'CodexProfileFunctions saved runtime'
                }
            }
        }
    }
    else {
        $saved = Get-22scSourceDefinition -FunctionName $functionName -Paths $SourcePath
        if ($saved) {
            $definition = $saved.Definition
            $source = $saved.Source
        }
    }

    if ([string]::IsNullOrWhiteSpace($definition)) {
        throw "22sc: '$functionName' was not found in this session or -SourcePath."
    }
    if ($definition -match '(?i)\bInvoke-ProfileLazyFunction\b') {
        throw "22sc: '$functionName' is a lazy dispatcher wrapper. Supply its real source via -SourcePath; a wrapper would generate a recursive script."
    }

    $outputFile = Join-Path $destination ($functionName + '.ps1')
    if ((Test-Path -LiteralPath $outputFile -PathType Leaf) -and -not $Force) {
        throw "22sc: '$outputFile' already exists. Use -Force to overwrite it."
    }

    $scriptText = @(
        "# Generated by 22sc from function '$functionName' ($(Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))."
        '# Captured function body; intentionally independent of CodexProfileFunctions.'
        $definition
        ''
        "if (`$MyInvocation.InvocationName -ne '.') {"
        "    & '$functionName' @args"
        '}'
        ''
    ) -join [Environment]::NewLine
    $tokens = $null
    $errors = $null
    [System.Management.Automation.Language.Parser]::ParseInput($scriptText, [ref] $tokens, [ref] $errors) | Out-Null
    if ($errors -and $errors.Count -gt 0) {
        throw "22sc: generated '$functionName' failed syntax validation: $($errors[0].Message)"
    }
    $plans.Add([pscustomobject]@{ Function = $functionName; Source = $source; Path = $outputFile; Text = $scriptText })
}

# No target changes occur until all requested functions have been validated.
foreach ($plan in $plans) {
    [System.IO.File]::WriteAllText($plan.Path, $plan.Text, (New-Object System.Text.UTF8Encoding($false)))
    [pscustomobject]@{
        Function = $plan.Function
        Source   = $plan.Source
        Path     = $plan.Path
        Lines    = @([System.IO.File]::ReadAllLines($plan.Path)).Count
    }
}
