# Generated by 2sc from function 'getoc2' (2026-08-13 02:27:14).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function getoc2 {
    $ErrorActionPreference = 'Stop'

    function Invoke-OcRetry([scriptblock]$Block, [int]$Attempts = 3) {
        for ($i = 1; $i -le $Attempts; $i++) {
            try { & $Block; return } catch {
                if ($i -eq $Attempts) { throw }
                Start-Sleep -Seconds (2 * $i)
            }
        }
    }

    function Test-OcProp([object]$Obj, [string]$Name) {
        return ($null -ne $Obj -and $null -ne $Obj.PSObject -and $null -ne $Obj.PSObject.Properties[$Name])
    }

    function Resolve-OcToolPath {
        param(
            [string[]]$Candidates,
            [string[]]$CommandNames
        )

        foreach ($candidate in $Candidates) {
            if ($candidate -and (Test-Path -LiteralPath $candidate -PathType Leaf)) {
                return $candidate
            }
        }
        foreach ($commandName in $CommandNames) {
            foreach ($command in (Get-Command $commandName -All -ErrorAction SilentlyContinue)) {
                if ($command.Source -and
                    $command.Source -notmatch 'WindowsApps' -and
                    (Test-Path -LiteralPath $command.Source -PathType Leaf)) {
                    return $command.Source
                }
            }
        }
        return $null
    }

    $nodeExe = Resolve-OcToolPath -Candidates @(
        (Join-Path ${env:ProgramFiles} 'nodejs\node.exe'),
        (Join-Path ${env:ProgramFiles(x86)} 'nodejs\node.exe')
    ) -CommandNames @('node.exe', 'node')
    $npmCmd = Resolve-OcToolPath -Candidates @(
        (Join-Path ${env:ProgramFiles} 'nodejs\npm.cmd'),
        (Join-Path ${env:ProgramFiles(x86)} 'nodejs\npm.cmd'),
        (Join-Path ${env:APPDATA} 'npm\npm.cmd')
    ) -CommandNames @('npm.cmd', 'npm')
    if (-not $nodeExe -or -not $npmCmd) {
        throw "GETOC2: Node.js/npm is unavailable (node=$nodeExe npm=$npmCmd)."
    }

    $bootstrapMutex = New-Object Threading.Mutex($false, 'Local\GetOc2BootstrapV2')
    $bootstrapLockTaken = $false
    try {
        try {
            $bootstrapLockTaken = $bootstrapMutex.WaitOne(300000)
        } catch [Threading.AbandonedMutexException] {
            $bootstrapLockTaken = $true
        }
        if (-not $bootstrapLockTaken) {
            throw 'GETOC2: timed out waiting for another OpenCode bootstrap.'
        }

        Write-Output 'GETOC2_PROGRESS stage=starting'

        # 1) Force a permanent npm global prefix on the C: drive so opencode
        #    survives Windows reboots (never a temp/F:-drive location).
        $npmGlobalPrefix = Join-Path $env:LOCALAPPDATA 'npm-global'
        $nodeDirectory = Split-Path -Parent $nodeExe
        New-Item -ItemType Directory -Force -Path $npmGlobalPrefix | Out-Null

        # Put the real npm/OpenCode paths before WinGet shims. This also repairs
        # already-open shells whose PATH predates the Node.js installation.
        $priorityPathEntries = @($npmGlobalPrefix, $nodeDirectory)
        $processPathParts = @(($env:Path -split ';') | Where-Object {
            $part = $_.Trim()
            $part -and @($priorityPathEntries | Where-Object {
                $_.TrimEnd('\') -ieq $part.TrimEnd('\')
            }).Count -eq 0
        })
        $env:Path = (($priorityPathEntries + $processPathParts) -join ';')

        $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
        $userPathParts = @(($userPath -split ';') | Where-Object {
            $part = $_.Trim()
            $part -and @($priorityPathEntries | Where-Object {
                $_.TrimEnd('\') -ieq $part.TrimEnd('\')
            }).Count -eq 0
        })
        $newUserPath = (($priorityPathEntries + $userPathParts) -join ';')
        if ($newUserPath -ne $userPath) {
            [Environment]::SetEnvironmentVariable('Path', $newUserPath, 'User')
        }
        & $npmCmd config set prefix $npmGlobalPrefix | Out-Null

        # 2) Install the opencode CLI only when the real command is absent or
        #    broken. Sessions queued on the mutex re-check here, so only the
        #    first bootstrap performs network/package work.
        $openCodeCmd = Join-Path $npmGlobalPrefix 'opencode.cmd'
        $openCodeReady = $false
        if (Test-Path -LiteralPath $openCodeCmd -PathType Leaf) {
            try {
                $openCodeVersion = (& $openCodeCmd --version 2>$null) -join ' '
                $openCodeHelp = ((& $openCodeCmd models --help 2>&1) -join "`n") -replace "`e\[[0-9;]*m", ''
                $openCodeReady = ($openCodeVersion -match '^\s*\d+\.\d+\.\d+\s*$' -and
                    $openCodeHelp -match '(?m)^\s*opencode\s+models\b')
            } catch {
                $openCodeReady = $false
            }
        }
        if (-not $openCodeReady) {
            Write-Output 'GETOC2_PROGRESS stage=installing-opencode'
            Invoke-OcRetry { & $npmCmd install -g opencode-ai | Out-Null }
        } else {
            Write-Output "GETOC2_PROGRESS stage=opencode-current path=$openCodeCmd version=$openCodeVersion"
        }

        # Resolve and verify the installed opencode command.
        $openCodeCmd = $null
        foreach ($candidate in @(
            (Join-Path $npmGlobalPrefix 'opencode.cmd'),
            (Join-Path $npmGlobalPrefix 'opencode'),
            (Join-Path ${env:APPDATA} 'npm\opencode.cmd'),
            (Join-Path ${env:ProgramFiles} 'nodejs\opencode.cmd')
        )) {
            if (Test-Path -LiteralPath $candidate -PathType Leaf) { $openCodeCmd = $candidate; break }
        }
        if (-not $openCodeCmd) {
            $ocCmd = Get-Command opencode -CommandType Application -ErrorAction SilentlyContinue
            if ($ocCmd) { $openCodeCmd = $ocCmd.Source }
        }
        if (-not $openCodeCmd) {
            throw 'GETOC2: opencode CLI installed but no runnable command found on PATH.'
        }
        try {
            $verifiedOpenCodeVersion = (& $openCodeCmd --version 2>$null) -join ' '
            $verifiedOpenCodeHelp = ((& $openCodeCmd models --help 2>&1) -join "`n") -replace "`e\[[0-9;]*m", ''
            if ($verifiedOpenCodeVersion -notmatch '^\s*\d+\.\d+\.\d+\s*$' -or
                $verifiedOpenCodeHelp -notmatch '(?m)^\s*opencode\s+models\b') {
                throw "unexpected version output: $verifiedOpenCodeVersion"
            }
        } catch {
            throw "GETOC2: installed opencode command is not runnable: $openCodeCmd ($($_.Exception.Message))"
        }
        Write-Output "GETOC2_PROGRESS stage=opencode-ready path=$openCodeCmd version=$verifiedOpenCodeVersion"

        # 3) Install the exact browser plugin only when it is absent, incomplete,
        #    or at the wrong version.
        $pkg = '@different-ai/opencode-browser'
        $ver = '4.6.1'
        $groot = (& $npmCmd root -g).Trim()
        $pkgRoot = Join-Path $groot '@different-ai\opencode-browser'
        $pkgJsonPath = Join-Path $pkgRoot 'package.json'
        $browserPluginReady = $false
        if (Test-Path -LiteralPath $pkgJsonPath -PathType Leaf) {
            try {
                $pkgJson = Get-Content -LiteralPath $pkgJsonPath -Raw | ConvertFrom-Json
                $browserPluginReady = (
                    [string]$pkgJson.version -eq $ver -and
                    (Test-Path -LiteralPath (Join-Path $pkgRoot 'bin\broker.cjs') -PathType Leaf) -and
                    (Test-Path -LiteralPath (Join-Path $pkgRoot 'bin\native-host.cjs') -PathType Leaf) -and
                    (Test-Path -LiteralPath (Join-Path $pkgRoot 'extension\manifest.json') -PathType Leaf)
                )
            } catch {
                $browserPluginReady = $false
            }
        }
        if (-not $browserPluginReady) {
            Write-Output 'GETOC2_PROGRESS stage=installing-browser-plugin'
            Invoke-OcRetry { & $npmCmd install -g "$pkg@$ver" --silent | Out-Null }
        } else {
            Write-Output "GETOC2_PROGRESS stage=browser-plugin-current version=$ver"
        }
        if (-not (Test-Path -LiteralPath $pkgRoot -PathType Container)) {
            throw "Package root missing: $pkgRoot"
        }

        $base = Join-Path $env:USERPROFILE '.opencode-browser'
        $extDst = Join-Path $base 'extension'
        $hostName = 'com.opencode.browser_automation'
        $wrapper = Join-Path $base 'host-wrapper.cmd'
        $nativeManifest = Join-Path $base "$hostName.json"
        $cfgDir = Join-Path $env:USERPROFILE '.config\opencode'
        $cfgPath = Join-Path $cfgDir 'opencode.json'
        $buildPromptPath = Join-Path $cfgDir 'build-prompt.txt'

        # A completed first bootstrap leaves all of these durable receipts.
        # Waiters can return immediately instead of serially recopying the
        # extension, touching registry keys, and rewriting JSON.
        if ($openCodeReady -and $browserPluginReady) {
            $nativeHostReady = $false
            $configReady = $false
            try {
                $nativeHostJson = Get-Content -LiteralPath $nativeManifest -Raw | ConvertFrom-Json
                $registeredManifest = (
                    Get-ItemProperty -LiteralPath "HKCU:\Software\Google\Chrome\NativeMessagingHosts\$hostName" -ErrorAction Stop
                ).'(default)'
                $nativeHostReady = (
                    (Test-Path -LiteralPath $wrapper -PathType Leaf) -and
                    (Test-Path -LiteralPath (Join-Path $base 'native-host.cjs') -PathType Leaf) -and
                    (Test-Path -LiteralPath (Join-Path $base 'broker.cjs') -PathType Leaf) -and
                    (Test-Path -LiteralPath (Join-Path $extDst 'manifest.json') -PathType Leaf) -and
                    $nativeHostJson.name -eq $hostName -and
                    $nativeHostJson.path -eq $wrapper -and
                    $registeredManifest -eq $nativeManifest
                )
            } catch {
                $nativeHostReady = $false
            }
            try {
                $currentConfig = Get-Content -LiteralPath $cfgPath -Raw | ConvertFrom-Json
                $configReady = (
                    @($currentConfig.plugin) -contains $pkg -and
                    (Test-Path -LiteralPath $buildPromptPath -PathType Leaf)
                )
            } catch {
                $configReady = $false
            }
            if ($nativeHostReady -and $configReady) {
                Write-Output "GETOC2_PROGRESS stage=bootstrap-current opencode=$verifiedOpenCodeVersion browser=$ver"
                Write-Output 'GETOC2_OK'
                Write-Output "GETOC2_DONE: opencode + browser plugin installed permanently (bin=$npmGlobalPrefix)"
                return
            }
        }

    New-Item -ItemType Directory -Force -Path $base, $extDst | Out-Null
    Copy-Item -Recurse -Force (Join-Path $pkgRoot 'extension\*') $extDst

    $brokerSrc = Join-Path $pkgRoot 'bin\broker.cjs'
    $hostSrc = Join-Path $pkgRoot 'bin\native-host.cjs'
    foreach ($p in @($brokerSrc, $hostSrc)) {
        if (-not (Test-Path $p)) { throw "Missing required file: $p" }
    }
    Copy-Item -Force $brokerSrc (Join-Path $base 'broker.cjs')
    Copy-Item -Force $hostSrc (Join-Path $base 'native-host.cjs')

    $node = $nodeExe
    "@echo off`r`n`"$node`" `"$base\native-host.cjs`"`r`n" | Set-Content -Encoding ASCII $wrapper

    $manifestObj = Get-Content -Raw (Join-Path $pkgRoot 'extension\manifest.json') | ConvertFrom-Json
    if ([string]::IsNullOrWhiteSpace($manifestObj.key)) { throw 'manifest.key missing' }
    $keyBytes = [Convert]::FromBase64String(($manifestObj.key -replace '\s', ''))
    $hash = [Security.Cryptography.SHA256]::Create().ComputeHash($keyBytes)[0..15]
    $extId = ($hash | ForEach-Object {
        $hi = [int]($_ -shr 4); $lo = [int]($_ -band 15)
        ([char]([int](97 + $hi))).ToString() + ([char]([int](97 + $lo))).ToString()
    }) -join ''
    [pscustomobject]@{
        name = $hostName
        description = 'OpenCode Browser native messaging host'
        path = $wrapper
        type = 'stdio'
        allowed_origins = @("chrome-extension://$extId/")
    } | ConvertTo-Json -Depth 5 | Set-Content -Encoding ASCII $nativeManifest

    foreach ($k in @(
        'HKCU\Software\Google\Chrome\NativeMessagingHosts',
        'HKCU\Software\Chromium\NativeMessagingHosts',
        'HKCU\Software\BraveSoftware\Brave-Browser\NativeMessagingHosts',
        'HKCU\Software\Microsoft\Edge\NativeMessagingHosts'
    )) {
        reg add "$k\$hostName" /ve /t REG_SZ /d "$nativeManifest" /f | Out-Null
    }

    # 4) Add the plugin to opencode.json without deleting the existing
    #    NVIDIA provider + API key.
    New-Item -ItemType Directory -Force -Path $cfgDir | Out-Null
    $cfg = if (Test-Path $cfgPath) {
        try { Get-Content -Raw $cfgPath | ConvertFrom-Json } catch { [pscustomobject]@{} }
    } else { [pscustomobject]@{} }
    if ($null -eq $cfg -or $cfg -isnot [psobject]) { $cfg = [pscustomobject]@{} }
    if (-not (Test-OcProp $cfg '$schema')) {
        $cfg | Add-Member -NotePropertyName '$schema' -NotePropertyValue 'https://opencode.ai/config.json' -Force
    }
    $plugins = @()
    if (Test-OcProp $cfg 'plugin') {
        if ($cfg.plugin -is [System.Array]) { $plugins = @($cfg.plugin) }
        elseif ($null -ne $cfg.plugin -and [string]$cfg.plugin -ne '') { $plugins = @([string]$cfg.plugin) }
    }
    if ($plugins -notcontains $pkg) { $plugins += $pkg }
    if (Test-OcProp $cfg 'plugin') { $cfg.plugin = $plugins }
    else { $cfg | Add-Member -NotePropertyName plugin -NotePropertyValue $plugins -Force }
    $cfg | ConvertTo-Json -Depth 10 | Set-Content -Encoding UTF8 $cfgPath

    # Ensure the build agent's prompt file exists (referenced by opencode.json)
    # so opencode never refuses to start with a 'bad file reference' error.
    if (-not (Test-Path -LiteralPath $buildPromptPath -PathType Leaf)) {
        $buildPromptDir = Split-Path -Parent $buildPromptPath
        if (-not (Test-Path -LiteralPath $buildPromptDir -PathType Container)) {
            New-Item -ItemType Directory -Force -Path $buildPromptDir | Out-Null
        }
        $defaultBuildPrompt = @'
# Build Agent Rules

You are the build agent. You turn requests into real, working, verified code.

## Non-negotiable rules

1. ALWAYS test what you create: after creating or modifying ANY file, run or test it to prove it works.
2. ALWAYS report the full path of every file you create or modify. Format: FULL PATH: C:\path\to\file
3. NEVER create generic garbage: produce real, complete, working code with proper error handling.
4. ALWAYS show real-time progress: state what you are doing at each step before doing it.
5. PowerShell 5 compatibility: on Windows, scripts MUST work in Windows PowerShell 5.1 - no ??, no &&, no AsHashtable; use try/catch blocks.
6. Never leave broken or half-finished work. If something cannot be completed, say exactly what is blocking it.

Use any tool you need to verify your work. When the task is done, summarize exactly what changed and how it was verified.
'@
        $defaultBuildPrompt | Set-Content -LiteralPath $buildPromptPath -Encoding UTF8
        Write-Host "GETOC2_PROGRESS stage=build-prompt-created path=$buildPromptPath"
    }

        Write-Output 'GETOC2_OK'
        Write-Output "GETOC2_DONE: opencode + browser plugin installed permanently (bin=$npmGlobalPrefix)"
    } finally {
        if ($bootstrapLockTaken) {
            [void]$bootstrapMutex.ReleaseMutex()
        }
        $bootstrapMutex.Dispose()
    }
}


if ($MyInvocation.InvocationName -ne '.') {
    & 'getoc2' @args
}
