# Generated by 2sc from function 'Invoke-DKillFastHardDeleteDockerVhd' (2026-08-12 22:06:52).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from.
if (-not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)) {
    $__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-DKillFastHardDeleteDockerVhd {
    [CmdletBinding()]
    param([string]$ConfirmFactoryReset='')
    if ($ConfirmFactoryReset -cne 'ERASE-ALL-DOCKER-DATA') {
        Write-Warning 'Direct Docker VHD deletion is blocked. The only destructive route requires -ConfirmFactoryReset ERASE-ALL-DOCKER-DATA.'
        $global:LASTEXITCODE = 2
        return $false
    }
    & 'F:\study\Platforms\windows\functions\dkill.ps1' -FactoryReset -ConfirmFactoryReset $ConfirmFactoryReset -NoRestart
    return ($LASTEXITCODE -eq 0)
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-DKillFastHardDeleteDockerVhd' @args
}
