# Generated by 2sc from function 'Invoke-DKillFastReleaseDockerVhdLocks' (2026-08-12 22:06:48).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from.
if (-not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)) {
    $__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-DKillFastReleaseDockerVhdLocks {
    [CmdletBinding()]
    param([ValidateRange(300,30000)][int]$Milliseconds=2500)
    Write-Host 'Legacy VHD-lock helper is protected: using bounded preserving Docker VMM recovery.' -ForegroundColor Cyan
    & 'F:\study\Platforms\windows\functions\dkill.ps1'
    [pscustomobject]@{Succeeded=($LASTEXITCODE -eq 0);Skipped=$false;Actions=@('preserving-vmm-recovery');Failures=@()}
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-DKillFastReleaseDockerVhdLocks' @args
}
