# Generated by 2sc from function 'Invoke-MmenuDockerLogin' (2026-08-13 02:28:41).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-MmenuDockerLogin {
    [CmdletBinding()]
    param()
    $helper = 'C:\Program Files\Docker\Docker\resources\bin\docker-credential-desktop.exe'
    if (-not (Test-Path -LiteralPath $helper -PathType Leaf)) {
        Write-Warning "mmenu: Docker credential helper not found: $helper"
        return $false
    }
    $info = New-Object Diagnostics.ProcessStartInfo
    $info.FileName = $helper
    $info.Arguments = 'list'
    $info.UseShellExecute = $false
    $info.CreateNoWindow = $true
    $info.RedirectStandardOutput = $true
    $info.RedirectStandardError = $true
    $process = [Diagnostics.Process]::Start($info)
    if (-not $process.WaitForExit(3000)) {
        try { $process.Kill() } catch { }
        Write-Warning 'mmenu: Docker credential lookup timed out.'
        return $false
    }
    if ($process.ExitCode -ne 0) { return $false }
    try {
        $credentials = $process.StandardOutput.ReadToEnd() | ConvertFrom-Json -ErrorAction Stop
        return @($credentials.PSObject.Properties | Where-Object {
            $_.Name -in @('https://index.docker.io/v1/', 'https://dhi.io', 'index.docker.io')
        }).Count -gt 0
    } catch {
        Write-Warning ("mmenu: Docker credential lookup failed: {0}" -f $_.Exception.Message)
        return $false
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-MmenuDockerLogin' @args
}
