# Generated by 2sc from function 'test-all-docker-configs' (2026-08-13 00:46:28).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function test-all-docker-configs {
    [CmdletBinding()]
    param()
    $enforcer = 'F:\study\Platforms\windows\functions\Set-DockerHyperV.ps1'
    & $enforcer -Label 'TEST ALL DOCKER CONFIGS (Docker VMM)' -Color 'Cyan' | Out-Host
    if (-not $?) { throw 'Docker VMM enforcement failed.' }
    $settingsPath = Join-Path $env:APPDATA 'Docker\settings-store.json'
    $settings = [IO.File]::ReadAllText($settingsPath) | ConvertFrom-Json -ErrorAction Stop
    if (-not [bool]$settings.UseLibkrun -or [bool]$settings.WslEngineEnabled -or [bool]$settings.UseVirtualizationFramework -or [bool]$settings.UseResourceSaver -or [int]$settings.MemoryMiB -ne 33792) {
        throw 'Docker settings are not the required maximum-performance VMM configuration.'
    }
    $sailor = Get-Process -Name 'com.docker.sailor' -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $sailor) { throw 'Docker VMM process com.docker.sailor is not running.' }
    foreach ($number in 1..30) {
        $presetPath = "F:\study\Platforms\windows\functions\docker$number.ps1"
        $presetText = [IO.File]::ReadAllText($presetPath)
        if ($presetText -match '(?i)wsl\.exe|\.wslconfig|DockerDesktopVM') { throw "Legacy backend route remains in docker$number." }
    }
    $dockerExe = 'C:\Program Files\Docker\Docker\resources\bin\docker.exe'
    $info = New-Object Diagnostics.ProcessStartInfo
    $info.FileName = $dockerExe
    $info.Arguments = 'version --format "{{.Server.Version}}"'
    $info.UseShellExecute = $false
    $info.CreateNoWindow = $true
    $info.RedirectStandardOutput = $true
    $info.RedirectStandardError = $true
    $process = [Diagnostics.Process]::Start($info)
    if (-not $process.WaitForExit(15000)) { try { $process.Kill() } catch {}; throw 'Docker daemon verification exceeded 15 seconds.' }
    $serverVersion = $process.StandardOutput.ReadToEnd().Trim()
    $serverError = $process.StandardError.ReadToEnd().Trim()
    if ($process.ExitCode -ne 0 -or [string]::IsNullOrWhiteSpace($serverVersion)) { throw "Docker daemon verification failed: $serverError" }
    Write-Host ("ALL_DOCKER_CONFIGS_VMM_OK presets=30 sailor_pid={0} server={1}" -f $sailor.Id,$serverVersion) -ForegroundColor Green
    $global:LASTEXITCODE = 0
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'test-all-docker-configs' @args
}
